controller_manager:
  ros__parameters:
    update_rate: 50
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    effort_controller:
      type: effort_controllers/JointGroupEffortController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster


effort_controller:
  ros__parameters:
    joints:
      - l_hip_yaw
      - l_hip_roll
      - l_hip_pitch
      - l_knee
      - l_ank_roll
      - l_ank_pitch
      - r_hip_yaw
      - r_hip_roll
      - r_hip_pitch
      - r_knee
      - r_ank_roll
      - r_ank_pitch
      - l_sho_pitch
      - l_sho_roll
      - l_el
      - r_sho_pitch
      - r_sho_roll
      - r_el
      - head_pan
      - head_tilt


    allow_partial_joints_goal: false
    open_loop_control: false
    # gains:
    #   l_hip_yaw:
    #     # pid: {p: 50.0, i: 0.0, d: 0.0}
    #     p:50.0
    #     i:0.0
    #     d:0.0

    #   l_hip_roll:
    #     # pid: {p: 50.0, i: 0.0, d: 0.0}
    #     p:50.0
    #     i:0.0
    #     d:0.0

    #   l_hip_pitch:  
    #     # pid: {p: 50.0, i: 0.0, d: 0.0}
    #     p:50.0
    #     i:0.0
    #     d:0.0

    #   l_knee:
    #     # pid: {p: 50.0, i: 0.0, d: 0.0}
    #     p:50.0
    #     i:0.0
    #     d:0.0

    #   l_ank_roll:
    #     # pid: {p: 50.0, i: 0.0, d: 0.0}
    #     p:50.0
    #     i:0.0
    #     d:0.0

    #   l_ank_pitch:
    #     # pid: {p: 50.0, i: 0.0, d: 0.0}
    #     p:50.0
    #     i:0.0
    #     d:0.0

    #   # Right Leg ---------------------------------------------------

    #   r_hip_yaw:
    #     # pid: {p: 50.0, i: 0.0, d: 0.0}
    #     p:50.0
    #     i:0.0
    #     d:0.0

    #   r_hip_roll:
    #     # pid: {p: 50.0, i: 0.0, d: 0.0}
    #     p:50.0
    #     i:0.0
    #     d:0.0

    #   r_hip_pitch:
    #     # pid: {p: 50.0, i: 0.0, d: 0.0}
    #     p:50.0
    #     i:0.0
    #     d:0.0

    #   r_knee:
    #     # pid: {p: 50.0, i: 0.0, d: 0.0}
    #     p:50.0
    #     i:0.0
    #     d:0.0

    #   r_ank_roll:
    #     # pid: {p: 50.0, i: 0.0, d: 0.0}
    #     p:50.0
    #     i:0.0
    #     d:0.0

    #   r_ank_pitch:
    #     # pid: {p: 50.0, i: 0.0, d: 0.0}
    #     p:50.0
    #     i:0.0
    #     d:0.0

    #   # Left Arm ---------------------------------------------------

    #   l_sho_pitch:
    #     p:10.0
    #     i:0.0
    #     d:0.0
        

    #   l_sho_roll:
    #     p:10.0
    #     i:0.0
    #     d:0.0
        

    #   l_el:
    #     p:10.0
    #     i:0.0
    #     d:0.0
        

    #   # Right Arm ---------------------------------------------------

    #   r_sho_pitch:
    #     p:10.0
    #     i:0.0
    #     d:0.0
        

    #   r_sho_roll:
    #     p:10.0
    #     i:0.0
    #     d:0.0
        

    #   r_el:
    #     p:10.0
    #     i:0.0
    #     d:0.0
        

    #   # Head ---------------------------------------------------

    #   head_pan:
    #     p:5.0
    #     i:0.0
    #     d:0.0

    #   head_tilt:
    #     p:5.0
    #     i:0.0
    #     d:0.0