###########################################
#   DYNAMIXEL MX28 (2.0) CONTROL TABLE    #
###########################################

DXL_MX28_MODEL_NUMBER_ADDR          = 0
DXL_MX28_MODEL_NUMBER_SIZE          = 2

DXL_MX28_ID_ADDR                    = 7
DXL_MX28_ID_SIZE                    = 1

DXL_MX28_BAUDRATE_ADDR              = 8
DXL_MX28_BAUDRATE_SIZE              = 1

DXL_MX28_DRIVE_MODE_ADDR            = 10
DXL_MX28_DRIVE_MODE_SIZE            = 1

DXL_MX28_OPERATING_MODE_ADDR        = 11
DXL_MX28_OPERATING_MODE_SIZE        = 1

DXL_MX28_HOMING_OFFSET_ADDR         = 20
DXL_MX28_HOMING_OFFSET_SIZE         = 4

DXL_MX28_TORQUE_ENABLE_ADDR         = 64
DXL_MX28_TORQUE_ENABLE_SIZE         = 1

DXL_MX28_LED_ADDR                   = 65
DXL_MX28_LED_SIZE                   = 1

DXL_MX28_GOAL_VELOCITY_ADDR         = 104
DXL_MX28_GOAL_VELOCITY_SIZE         = 4

DXL_MX28_PROFILE_ACCELERATION_ADDR  = 108
DXL_MX28_PROFILE_ACCELERATION_SIZE  = 4

DXL_MX28_PROFILE_VELOCITY_ADDR      = 112
DXL_MX28_PROFILE_VELOCITY_SIZE      = 4

DXL_MX28_GOAL_POSITION_ADDR         = 116
DXL_MX28_GOAL_POSITION_SIZE         = 4

DXL_MX28_MOVING_ADDR                = 122
DXL_MX28_MOVING_SIZE                = 1

DXL_MX28_PRESENT_LOAD_ADDR          = 126
DXL_MX28_PRESENT_LOAD_SIZE          = 2

DXL_MX28_PRESENT_VELOCITY_ADDR      = 128
DXL_MX28_PRESENT_VELOCITY_SIZE      = 4

DXL_MX28_PRESENT_POSITION_ADDR      = 132
DXL_MX28_PRESENT_POSITION_SIZE      = 4

DXL_MX28_PRESENT_INPUT_VOLTAGE_ADDR = 144
DXL_MX28_PRESENT_INPUT_VOLTAGE_SIZE = 2

DXL_MX28_PRESENT_TEMPERATURE_ADDR   = 146
DXL_MX28_PRESENT_TEMPERATURE_SIZE   = 1

###########################################
#   DYNAMIXEL MX64 (2.0) CONTROL TABLE    #
###########################################

DXL_MX64_MODEL_NUMBER_ADDR          = 0
DXL_MX64_MODEL_NUMBER_SIZE          = 2

DXL_MX64_ID_ADDR                    = 7
DXL_MX64_ID_SIZE                    = 1

DXL_MX64_BAUDRATE_ADDR              = 8
DXL_MX64_BAUDRATE_SIZE              = 1

DXL_MX64_DRIVE_MODE_ADDR            = 10
DXL_MX64_DRIVE_MODE_SIZE            = 1

DXL_MX64_OPERATING_MODE_ADDR        = 11
DXL_MX64_OPERATING_MODE_SIZE        = 1

DXL_MX64_HOMING_OFFSET_ADDR         = 20
DXL_MX64_HOMING_OFFSET_SIZE         = 4

DXL_MX64_TORQUE_ENABLE_ADDR         = 64
DXL_MX64_TORQUE_ENABLE_SIZE         = 1

DXL_MX64_LED_ADDR                   = 65
DXL_MX64_LED_SIZE                   = 1

DXL_MX64_GOAL_VELOCITY_ADDR         = 104
DXL_MX64_GOAL_VELOCITY_SIZE         = 4

DXL_MX64_PROFILE_ACCELERATION_ADDR  = 108
DXL_MX64_PROFILE_ACCELERATION_SIZE  = 4

DXL_MX64_PROFILE_VELOCITY_ADDR      = 112
DXL_MX64_PROFILE_VELOCITY_SIZE      = 4

DXL_MX64_GOAL_POSITION_ADDR         = 116
DXL_MX64_GOAL_POSITION_SIZE         = 4

DXL_MX64_MOVING_ADDR                = 122
DXL_MX64_MOVING_SIZE                = 1

DXL_MX64_PRESENT_LOAD_ADDR          = 126
DXL_MX64_PRESENT_LOAD_SIZE          = 2

DXL_MX64_PRESENT_VELOCITY_ADDR      = 128
DXL_MX64_PRESENT_VELOCITY_SIZE      = 4

DXL_MX64_PRESENT_POSITION_ADDR      = 132
DXL_MX64_PRESENT_POSITION_SIZE      = 4

DXL_MX64_PRESENT_INPUT_VOLTAGE_ADDR = 144
DXL_MX64_PRESENT_INPUT_VOLTAGE_SIZE = 2

DXL_MX64_PRESENT_TEMPERATURE_ADDR   = 146
DXL_MX64_PRESENT_TEMPERATURE_SIZE   = 1