set(_CATKIN_CURRENT_PACKAGE "robotis_framework")
set(robotis_framework_VERSION "0.2.9")
set(robotis_framework_MAINTAINER "Pyo <pyo@robotis.com>")
set(robotis_framework_PACKAGE_FORMAT "2")
set(robotis_framework_BUILD_DEPENDS )
set(robotis_framework_BUILD_EXPORT_DEPENDS )
set(robotis_framework_BUILDTOOL_DEPENDS "catkin")
set(robotis_framework_BUILDTOOL_EXPORT_DEPENDS )
set(robotis_framework_EXEC_DEPENDS "robotis_controller" "robotis_device" "robotis_framework_common")
set(robotis_framework_RUN_DEPENDS "robotis_controller" "robotis_device" "robotis_framework_common")
set(robotis_framework_TEST_DEPENDS )
set(robotis_framework_DOC_DEPENDS )
set(robotis_framework_URL_WEBSITE "http://wiki.ros.org/robotis_framework")
set(robotis_framework_URL_BUGTRACKER "https://github.com/ROBOTIS-GIT/ROBOTIS-Framework/issues")
set(robotis_framework_URL_REPOSITORY "https://github.com/ROBOTIS-GIT/ROBOTIS-Framework")
set(robotis_framework_DEPRECATED "")