dxl_baudrate: 1000000
dxl_u2d2_port: /dev/ttyUSB0
dxl_num: 20
dxl_id:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
- 12
- 13
- 14 
- 15
- 16
- 17
- 18
- 19
- 20
dxl_type:
- MX28
- MX28
- MX28
- MX28
- MX28
- MX28
- MX64
- MX64
- MX64
- MX64
- MX64
- MX64
- MX64
- MX64
- MX64
- MX64
- MX64
- MX64
- MX28
- MX28
joint_name:
- r_sho_pitch
- l_sho_pitch
- r_sho_roll
- l_sho_roll
- r_el
- l_el
- r_hip_yaw
- l_hip_yaw
- r_hip_roll
- l_hip_roll
- r_hip_pitch
- l_hip_pitch
- r_knee
- l_knee
- r_ank_pitch
- l_ank_pitch
- r_ank_roll
- l_ank_roll
- head_pan
- head_tilt