r_sho_pitch :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

l_sho_pitch :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

r_sho_roll :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

l_sho_roll :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

r_el :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

l_el :   # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

r_hip_yaw :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

l_hip_yaw :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

r_hip_roll :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

l_hip_roll :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

r_hip_pitch :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

l_hip_pitch :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

r_knee :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

l_knee :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

r_ank_pitch :  # XM-430
   return_delay_time        :  1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

l_ank_pitch :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

r_ank_roll :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

l_ank_roll :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

head_pan :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0

head_tilt :  # XM-430
   return_delay_time        : 1    # item name : value
   operating_mode           : 3
   min_position_limit       : 0
   max_position_limit       : 4095
   position_p_gain          : 850
   position_i_gain          : 0
   position_d_gain          : 0
